#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# tags with Ubuntu codename

echo "[***] Post_Push hook running"

# get Ubunut version from image's environmental variables, without running it
export UBUNTU_CODENAME=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{$value}} {{end}}' $IMAGE_NAME | grep -oP 'UBUNTU_VERSION=\K\w+')
echo "     Versions: $UBUNTU_CODENAME  $SOURCE_COMMIT"

docker tag $IMAGE_NAME $DOCKER_REPO:$UBUNTU_CODENAME
docker push $DOCKER_REPO:$PYTHON_VERSION_X_Y_Z

docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_COMMIT
docker push $DOCKER_REPO:$SOURCE_COMMIT
